FORMAT: 1A
HOST: https://nexpose.local:3780/insight/controls/api/

# ControlsInsight
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Assessments
## Assessment Collection [/assessments]
### Assessments [GET]

+ Response 200 (application/json)

            [
                {
                  "id": 1,
                  "assessing": false,
                  "highRiskAssetCount": 0,
                  "mediumRiskAssetCount": 24,
                  "lowRiskAssetCount": 0,
                  "totalAssetCount": 24,
                  "overallRiskScore": 4.004146038088617,
                  "timestamp": 1393184605912
                }
            ]

## Assessment [/assessments/{assessment_id}]
### Assessment by ID [GET]

+ Parameters
    + assessment_id (optional, integer, `1`) ... The ID of the assessment to retreive.

+ Response 200 (application/json)

            {
              "id": 1,
              "assessing": false,
              "highRiskAssetCount": 0,
              "mediumRiskAssetCount": 24,
              "lowRiskAssetCount": 0,
              "totalAssetCount": 24,
              "overallRiskScore": 4.004146038088617,
              "timestamp": 1393184605912
            }

# Group Search
## Assets [/assets/search?query={query}]
### Asset Search [GET]

+ Parameters
    + query (required, string, `10.4.19`) ... The free text query. This can be a full/partial hostname or IP address.

+ Response 200 (application/json)

        {
          "resources": {
            "uuid": "db899a57-347c-4df9-9ce2-6932dc4adf38>",
            "riskScore": 5.554266115196547,
            "riskLevel": "MEDIUM",
            "hostName": "CMMNCTR2K7R2-U",
            "ipaddress": "10.4.19.25"
          }
        }